####################################################################################################
# Creating container MySQL
####################################################################################################
mariadb:
    image: mariadb:10.2
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: sakila

####################################################################################################
# Creating container PHP
####################################################################################################
php:
    build: ./image/php/
    ports:
      - 9000:9000
    volumes:
      - ./www/lumen/:/var/www/html
    links:
      - mariadb

####################################################################################################
# Creating container (Nginx)
####################################################################################################
nginx:
    image: nginx:latest
    ports:
        - 8080:80
    volumes:
        - ./image/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

####################################################################################################
# Creating container phpmyadmin
####################################################################################################
phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - mariadb:db
    ports:
        - 8000:80
    environment:
        MYSQL_USERNAME: root
        MYSQL_ROOT_PASSWORD: root
